### ISSUE TITLE
Broken in Ubuntu 23.10

### ISSUE THREAD

**Issue by amiga-500** [PRATAP-KUMAR/customize-clock-on-lock-screen#1]
Although it installs fine in 23.10, it always disables itself when you try to enable it.  It was obviosuly working fine in 23.04 but this new upgrade to Ubuntu i guess crippled it.  Hope u'll fix

![aaa](https://github.com/PRATAP-KUMAR/customize-clock-on-lock-screen/assets/5191497/1a30273c-e71f-46c0-ba89-1b910afb72f6)

**Comment by PRATAP-KUMAR** [comment]
Hi, I will look into it.

**Comment by PRATAP-KUMAR** [comment]
Hi @amiga-500, I have just checked it in Ubuntu 23.10 with gnome-shell v45. It is working as expected.

> Although it installs fine in 23.10, it always disables itself when you try to enable it.
It is expected behavior. The extension will turn on when the screen is locked.

Can you remove this extension and then download the extension from https://extensions.gnome.org/extension/4663/customize-clock-on-lock-screen/ and install it and see.

![image](https://github.com/PRATAP-KUMAR/customize-clock-on-lock-screen/assets/40719899/3fe2b757-3e3e-40d9-907a-05816a3b95fa)

**Comment by amiga-500** [comment]
Hi there.  thx for the reply.  Still doesn't work for me.
It seems to be an Ubuntu 23.10 issue.  I am using Extension Manager with ur extension.
Here is a screencast of what it does.  Notice how the enable/disable toggle likes to turn itself off.  It never did this in Ubuntu 23.04.  It only started doing this for 23.10.  The other extensions dont have this issue.  I am starting to search through ur extensions js and meta details to see if i can figure out how to fix it.

![my-vine](https://github.com/PRATAP-KUMAR/customize-clock-on-lock-screen/assets/5191497/4b152e54-4ed1-4b67-8f4a-2fce4ecffe25)

**Comment by PRATAP-KUMAR** [comment]
Ho do you have any other extensions that somehow interact with lock screen?

For 23.04 I did not make the extension to use when it is locked. But for 23.10 I made this extension to be active only on lock screen. I did test it in my arch linux and ubuntu 23.10.

in 23.10 It is working but the time is not updating. Is your gnome-shell version 45.1 or 45.0

Thanks

**Comment by amiga-500** [comment]
Hi again.  Wow u're fast in your replies.  Was just coming back to update that you are right that, although the extension shows it is disabled (in Extensions Manager) it indeed is active when the lock screen is on.  So your extension DOES work corectly.  It was seeing it disabled that through me off.  I think when it was disabled i began to fiddle with the preferences which likely re-enabled the clock giving me the impression the your extension was not working when in fact it was.

So thanks very much!  Awesome extension :)
